services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PG_URL=postgresql://db:5432/taska
      - PG_USERNAME=taska
      - PG_PASSWORD=taska
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=taska
      - POSTGRES_USER=taska
      - POSTGRES_PASSWORD=taska
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge